# Generated by Django 4.1.2 on 2022-12-14 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('cantidadPersonas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('estadoReserva', models.CharField(choices=[('R', 'Reservado'), ('C', 'Completada'), ('A', 'Anulada'), ('N', 'No asisten')], max_length=32)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
    ]
