# Generated by Django 4.1.2 on 2022-12-21 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollosHermanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidadPersonas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='El minimo de reserva es 1'), django.core.validators.MaxValueValidator(limit_value=15, message='El maximo de reserva es 15')]),
        ),
    ]
