# Generated by Django 4.1.2 on 2022-12-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollosHermanos', '0003_alter_reserva_cantidadpersonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estadoReserva',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Completada', 'Completada'), ('Anulada', 'Anulada'), ('No asisten', 'No asisten')], max_length=32),
        ),
    ]
